version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: Laravel_E-commerce-nginx
    ports: ["80:80"]
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: [app, vite]

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: Laravel_E-commerce-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=laravel_ecommerce"
      - "DB_USERNAME=admin"
      - "DB_PASSWORD=admin"

  db:
    image: mysql:8.0
    container_name: Laravel_E-commerce-db
    restart: unless-stopped
    ports: ["3306:3306"]
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql

  # ... (bloco do 'db' acima)

  vite:
    # Use a MESMA imagem/build do serviço 'app'
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${PROJECT_NAME}-vite
    working_dir: /var/www/html
    ports: ["5173:5173"]
    volumes:
      - ./src:/var/www/html
    # O entrypoint agora usará o NPM instalado DENTRO da imagem do app
    entrypoint: ["npm", "run", "dev"]

  composer:
    image: composer:latest
    container_name: Laravel_E-commerce-composer
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ["composer"]

  artisan:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: Laravel_E-commerce-artisan
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "artisan"]
    depends_on: [db]
